project_name: kcl-controller

builds:
  - skip: true

release:
  prerelease: auto
  footer: |
    ## Container images
    
    - `docker.io/kcllang/{{.ProjectName}}:{{.Tag}}`
    - `ghcr.io/kcl-lang/{{.ProjectName}}:{{.Tag}}`
    
    Supported architectures: `linux/amd64`, `linux/arm64`.
    
    The container images are built on GitHub hosted runners and are signed with cosign and GitHub OIDC.

changelog:
  use: github-native

checksum:
  name_template: 'checksums.txt'

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source
